using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ZaferTurizm.Domain;

namespace ZaferTurizm.DataAccess.Configurations
{
    internal class CityData
    {
        public readonly static City Data01_Adana = new City() { Id = 1, Name = "Adana" };
        public readonly static City Data02_Adıyaman = new City() { Id = 2, Name = "Adıyaman" };
        public readonly static City Data03_Afyon = new City() { Id = 3, Name = "Afyon" };
        public readonly static City Data04_Ağrı = new City() { Id = 4, Name = "Ağrı" };
        public readonly static City Data05_Aksaray = new City() { Id = 5, Name = "Aksaray" };
        public readonly static City Data06_Amasya = new City() { Id = 6, Name = "Amasya" };
        public readonly static City Data07_Ankara = new City() { Id = 7, Name = "Ankara" };
        public readonly static City Data08_Antalya = new City() { Id = 8, Name = "Antalya" };
        public readonly static City Data09_Ardahan = new City() { Id = 9, Name = "Ardahan" };
        public readonly static City Data10_Artvin = new City() { Id = 10, Name = "Artvin" };
        public readonly static City Data11_Aydın = new City() { Id = 11, Name = "Aydın" };
        public readonly static City Data12_Balıkesir = new City() { Id = 12, Name = "Balıkesir" };
        public readonly static City Data13_Bartın = new City() { Id = 13, Name = "Bartın" };
        public readonly static City Data14_Batman = new City() { Id = 14, Name = "Batman" };
        public readonly static City Data15_Bayburt = new City() { Id = 15, Name = "Bayburt" };
        public readonly static City Data16_Bilecik = new City() { Id = 16, Name = "Bilecik" };
        public readonly static City Data17_Bingöl = new City() { Id = 17, Name = "Bingöl" };
        public readonly static City Data18_Bitlis = new City() { Id = 18, Name = "Bitlis" };
        public readonly static City Data19_Bolu = new City() { Id = 19, Name = "Bolu" };
        public readonly static City Data20_Burdur = new City() { Id = 20, Name = "Burdur" };
        public readonly static City Data21_Bursa = new City() { Id = 21, Name = "Bursa" };
        public readonly static City Data22_Çanakkale = new City() { Id = 22, Name = "Çanakkale" };
        public readonly static City Data23_Çankırı = new City() { Id = 23, Name = "Çankırı" };
        public readonly static City Data24_Çorum = new City() { Id = 24, Name = "Çorum" };
        public readonly static City Data25_Denizli = new City() { Id = 25, Name = "Denizli" };
        public readonly static City Data26_Diyarbakır = new City() { Id = 26, Name = "Diyarbakır" };
        public readonly static City Data27_Düzce = new City() { Id = 27, Name = "Düzce" };
        public readonly static City Data28_Edirne = new City() { Id = 28, Name = "Edirne" };
        public readonly static City Data29_Elazığ = new City() { Id = 29, Name = "Elazığ" };
        public readonly static City Data30_Erzincan = new City() { Id = 30, Name = "Erzincan" };
        public readonly static City Data31_Erzurum = new City() { Id = 31, Name = "Erzurum" };
        public readonly static City Data32_Eskişehir = new City() { Id = 32, Name = "Eskişehir" };
        public readonly static City Data33_Gaziantep = new City() { Id = 33, Name = "Gaziantep" };
        public readonly static City Data34_Giresun = new City() { Id = 34, Name = "Giresun" };
        public readonly static City Data35_Gümüşhane = new City() { Id = 35, Name = "Gümüşhane" };
        public readonly static City Data36_Hakkari = new City() { Id = 36, Name = "Hakkari" };
        public readonly static City Data37_Hatay = new City() { Id = 37, Name = "Hatay" };
        public readonly static City Data38_Iğdır = new City() { Id = 38, Name = "Iğdır" };
        public readonly static City Data39_Isparta = new City() { Id = 39, Name = "Isparta" };
        public readonly static City Data40_İstanbul = new City() { Id = 40, Name = "İstanbul" };
        public readonly static City Data41_İzmir = new City() { Id = 41, Name = "İzmir" };
        public readonly static City Data42_Kahramanmaraş = new City() { Id = 42, Name = "Kahramanmaraş" };
        public readonly static City Data43_Karabük = new City() { Id = 43, Name = "Karabük" };
        public readonly static City Data44_Karaman = new City() { Id = 44, Name = "Karaman" };
        public readonly static City Data45_Kars = new City() { Id = 45, Name = "Kars" };
        public readonly static City Data46_Kastamonu = new City() { Id = 46, Name = "Kastamonu" };
        public readonly static City Data47_Kayseri = new City() { Id = 47, Name = "Kayseri" };
        public readonly static City Data48_Kırıkkale = new City() { Id = 48, Name = "Kırıkkale" };
        public readonly static City Data49_Kırklareli = new City() { Id = 49, Name = "Kırklareli" };
        public readonly static City Data50_Kırşehir = new City() { Id = 50, Name = "Kırşehir" };
        public readonly static City Data51_Kilis = new City() { Id = 51, Name = "Kilis" };
        public readonly static City Data52_Kocaeli = new City() { Id = 52, Name = "Kocaeli" };
        public readonly static City Data53_Konya = new City() { Id = 53, Name = "Konya" };
        public readonly static City Data54_Kütahya = new City() { Id = 54, Name = "Kütahya" };
        public readonly static City Data55_Malatya = new City() { Id = 55, Name = "Malatya" };
        public readonly static City Data56_Manisa = new City() { Id = 56, Name = "Manisa" };
        public readonly static City Data57_Mardin = new City() { Id = 57, Name = "Mardin" };
        public readonly static City Data58_Mersin = new City() { Id = 58, Name = "Mersin" };
        public readonly static City Data59_Muğla = new City() { Id = 59, Name = "Muğla" };
        public readonly static City Data60_Muş = new City() { Id = 60, Name = "Muş" };
        public readonly static City Data61_Nevşehir = new City() { Id = 61, Name = "Nevşehir" };
        public readonly static City Data62_Niğde = new City() { Id = 62, Name = "Niğde" };
        public readonly static City Data63_Ordu = new City() { Id = 63, Name = "Ordu" };
        public readonly static City Data64_Osmaniye = new City() { Id = 64, Name = "Osmaniye" };
        public readonly static City Data65_Rize = new City() { Id = 65, Name = "Rize" };
        public readonly static City Data66_Sakarya = new City() { Id = 66, Name = "Sakarya" };
        public readonly static City Data67_Samsun = new City() { Id = 67, Name = "Samsun" };
        public readonly static City Data68_Siirt = new City() { Id = 68, Name = "Siirt" };
        public readonly static City Data69_Sinop = new City() { Id = 69, Name = "Sinop" };
        public readonly static City Data70_Sivas = new City() { Id = 70, Name = "Sivas" };
        public readonly static City Data71_Şanlıurfa = new City() { Id = 71, Name = "Şanlıurfa" };
        public readonly static City Data72_Şırnak = new City() { Id = 72, Name = "Şırnak" };
        public readonly static City Data73_Tekirdağ = new City() { Id = 73, Name = "Tekirdağ" };
        public readonly static City Data74_Tokat = new City() { Id = 74, Name = "Tokat" };
        public readonly static City Data75_Trabzon = new City() { Id = 75, Name = "Trabzon" };
        public readonly static City Data76_Tunceli = new City() { Id = 76, Name = "Tunceli" };
        public readonly static City Data77_Uşak = new City() { Id = 77, Name = "Uşak" };
        public readonly static City Data78_Van = new City() { Id = 78, Name = "Van" };
        public readonly static City Data79_Yalova = new City() { Id = 79, Name = "Yalova" };
        public readonly static City Data80_Yozgat = new City() { Id = 80, Name = "Yozgat" };
        public readonly static City Data81_Zonguldak = new City() { Id = 81, Name = "Zonguldak" };
    }
}
